Numpy

In [2]:
import numpy as np

In [4]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [6]:
b = np.array([3.4,5.4,6.0])
b

array([3.4, 5.4, 6. ])

In [7]:
a[1:]

array([2, 3])

In [8]:
a[0]

1

In [9]:
a[0:1]

array([1])

In [10]:
a[:-1]

array([1, 2])

In [12]:
b[[0,2]] #multi-indexing

array([3.4, 6. ])

# Array Types

In [13]:
b.dtype

dtype('float64')

In [14]:
a.dtype

dtype('int32')

Dimensions and Shapes

In [17]:
y = np.array([[2,5,6], [3,5,7]])
y

array([[2, 5, 6],
       [3, 5, 7]])

In [18]:
y.shape

(2, 3)

In [19]:
y.ndim

2

In [20]:
y.size

6

In [22]:
z = np.array([[[1,2],[3,4]],
              [[5,6],[7,8]]])
z              

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [23]:
z.shape

(2, 2, 2)

In [24]:
type(y[0])

numpy.ndarray

Indexing and slicing of matrices

In [25]:
c = np.array([[4,5,6],[9,6,4], [10,2,5]])

In [26]:
c[1]

array([9, 6, 4])

In [27]:
c[1][0]

9

In [29]:
c[0:2]

array([[4, 5, 6],
       [9, 6, 4]])

In [30]:
c[2,2]

5

In [31]:
c[:-1,:-1]

array([[4, 5],
       [9, 6]])

In [32]:
c[1] = np.array([22,15,3])

In [33]:
c

array([[ 4,  5,  6],
       [22, 15,  3],
       [10,  2,  5]])

summary statistics

In [34]:
d = np.array([6,5,7,9,3])

In [35]:
d.mean()

6.0

In [38]:
d.std()

2.0

In [39]:
d.var()

4.0

In [40]:
d.sum()

30

In [41]:
c.sum(axis = 1)

array([15, 40, 17])