Numpy

In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [3]:
b = np.array([3.4,5.4,6.0])
b

array([3.4, 5.4, 6. ])

In [4]:
a[1:]

array([2, 3])

In [5]:
a[0]

1

In [6]:
a[0:1]

array([1])

In [7]:
a[:-1]

array([1, 2])

In [8]:
b[[0,2]] #multi-indexing

array([3.4, 6. ])

# Array Types

In [9]:
b.dtype

dtype('float64')

In [10]:
a.dtype

dtype('int32')

Dimensions and Shapes

In [11]:
y = np.array([[2,5,6], [3,5,7]])
y

array([[2, 5, 6],
       [3, 5, 7]])

In [12]:
y.shape

(2, 3)

In [13]:
y.ndim

2

In [14]:
y.size

6

In [15]:
z = np.array([[[1,2],[3,4]],
              [[5,6],[7,8]]])
z              

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [16]:
z.shape

(2, 2, 2)

In [17]:
type(y[0])

numpy.ndarray

Indexing and slicing of matrices

In [18]:
c = np.array([[4,5,6],[9,6,4], [10,2,5]])

In [19]:
c[1]

array([9, 6, 4])

In [20]:
c[1][0]

9

In [21]:
c[0:2]

array([[4, 5, 6],
       [9, 6, 4]])

In [22]:
c[2,2]

5

In [23]:
c[:-1,:-1]

array([[4, 5],
       [9, 6]])

In [24]:
c[1] = np.array([22,15,3])

In [25]:
c

array([[ 4,  5,  6],
       [22, 15,  3],
       [10,  2,  5]])

summary statistics

In [26]:
d = np.array([6,5,7,9,3])

In [27]:
d.mean()

6.0

In [28]:
d.std()

2.0

In [29]:
d.var()

4.0

In [30]:
d.sum()

30

In [31]:
c.sum(axis = 1)

array([15, 40, 17])

Broadcasting and Vectorized operations

In [33]:
e = np.arange(4)
e

array([0, 1, 2, 3])

In [34]:
e + 5

array([5, 6, 7, 8])

In [35]:
e * 3

array([0, 3, 6, 9])

In [36]:
e ** 2

array([0, 1, 4, 9], dtype=int32)

In [37]:
e += 50
e

array([50, 51, 52, 53])

In [38]:
l = [1,3,5,7]
[i * 2 for i in l]

[2, 6, 10, 14]

In [39]:
f = np.array([3,5,7,9])
f+e

array([53, 56, 59, 62])

In [40]:
f*e

array([150, 255, 364, 477])

Boolean Arrays

In [41]:
e[[True, False, True, False]]

array([50, 52])

In [42]:
e > 51

array([False, False,  True,  True])

In [43]:
e[e > 51]

array([52, 53])

In [44]:
e.mean()

51.5

In [46]:
e[e > e.mean()]

array([52, 53])

In [47]:
e[~(e > e.mean())]

array([50, 51])

In [48]:
e[(e == 51) | (e==52)]

array([51, 52])

In [50]:
e[(e >= 51) & (e% 2 == 0)]

array([52])

In [52]:
f = np.random.randint(100, size =(3,3))
f

array([[44, 92, 36],
       [16, 81, 27],
       [ 0, 33, 39]])

In [53]:
f[np.array([[True, False, False], [True, True, False], [False, False, True]])]

array([44, 16, 81, 39])

In [54]:
f > 30

array([[ True,  True,  True],
       [False,  True, False],
       [False,  True,  True]])

In [55]:
f[f>30]

array([44, 92, 36, 81, 33, 39])

Linear Algebra

In [56]:
a = np.array([[2,4,6],[6,7,8],[9,12,15]])
b = np.array([[4,6],[7,8],[12,15]])

In [57]:
a.dot(b)

array([[108, 134],
       [169, 212],
       [300, 375]])

In [58]:
a @ b

array([[108, 134],
       [169, 212],
       [300, 375]])

In [59]:
b.T #transpose

array([[ 4,  7, 12],
       [ 6,  8, 15]])

Size of Objects in Memory

In [60]:
import sys

In [61]:
sys.getsizeof(1)

28

In [62]:
sys.getsizeof(1.1)

24

In [63]:
np.dtype(int).itemsize

4

In [64]:
sys.getsizeof([1])

72

Random

In [65]:
np.random.random(size=2)

array([0.04365972, 0.29614267])

In [66]:
np.random.normal(size=2)

array([ 0.21540421, -1.33435015])

In [67]:
np.random.rand(2,4)

array([[0.58345825, 0.4445696 , 0.30804973, 0.57271957],
       [0.55331818, 0.02573628, 0.30434821, 0.48784373]])

Reshape

In [69]:
np.arange(10).reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [70]:
np.arange(0,1,0.1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

Linspace

In [71]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

Empty

In [74]:
np.empty(4)

array([0.25, 0.5 , 0.75, 1.  ])

In [75]:
np.eye(8,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [76]:
np.eye(8,4, k=1)

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])