Numpy

In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [3]:
b = np.array([3.4,5.4,6.0])
b

array([3.4, 5.4, 6. ])

In [4]:
a[1:]

array([2, 3])

In [5]:
a[0]

1

In [6]:
a[0:1]

array([1])

In [7]:
a[:-1]

array([1, 2])

In [8]:
b[[0,2]] #multi-indexing

array([3.4, 6. ])

# Array Types

In [9]:
b.dtype

dtype('float64')

In [10]:
a.dtype

dtype('int32')

Dimensions and Shapes

In [11]:
y = np.array([[2,5,6], [3,5,7]])
y

array([[2, 5, 6],
       [3, 5, 7]])

In [12]:
y.shape

(2, 3)

In [13]:
y.ndim

2

In [14]:
y.size

6

In [15]:
z = np.array([[[1,2],[3,4]],
              [[5,6],[7,8]]])
z              

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [16]:
z.shape

(2, 2, 2)

In [17]:
type(y[0])

numpy.ndarray

Indexing and slicing of matrices

In [18]:
c = np.array([[4,5,6],[9,6,4], [10,2,5]])

In [19]:
c[1]

array([9, 6, 4])

In [20]:
c[1][0]

9

In [21]:
c[0:2]

array([[4, 5, 6],
       [9, 6, 4]])

In [22]:
c[2,2]

5

In [23]:
c[:-1,:-1]

array([[4, 5],
       [9, 6]])

In [24]:
c[1] = np.array([22,15,3])

In [25]:
c

array([[ 4,  5,  6],
       [22, 15,  3],
       [10,  2,  5]])

summary statistics

In [26]:
d = np.array([6,5,7,9,3])

In [27]:
d.mean()

6.0

In [28]:
d.std()

2.0

In [29]:
d.var()

4.0

In [30]:
d.sum()

30

In [31]:
c.sum(axis = 1)

array([15, 40, 17])

Broadcasting and Vectorized operations

In [33]:
e = np.arange(4)
e

array([0, 1, 2, 3])

In [34]:
e + 5

array([5, 6, 7, 8])

In [35]:
e * 3

array([0, 3, 6, 9])

In [36]:
e ** 2

array([0, 1, 4, 9], dtype=int32)

In [37]:
e += 50
e

array([50, 51, 52, 53])

In [38]:
l = [1,3,5,7]
[i * 2 for i in l]

[2, 6, 10, 14]

In [39]:
f = np.array([3,5,7,9])
f+e

array([53, 56, 59, 62])

In [40]:
f*e

array([150, 255, 364, 477])

Boolean Arrays